name: CI

strategy:
  matrix:
    node-version: [10.x, 12.x, 14.x, 15.x]

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: npm run build
    - name: test
      run: npm run test