name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  strategy:
    matrix:
      node-version: [14.x, 15.x]
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: npm run build
    - name: test
      run: npm run test